language: node_js
node_js:
- node
install:
- npm install -g yarn
- yarn
- yarn link
- yarn link babel-dts-generator
script:
- yarn run test
cache: yarn
deploy:
  provider: npm
  email: alxandr@alxandr.me
  api_key:
    secure: KrzERteWzDvwwThQdzPw7ZXDnVhVY8um5A9/lPeJj0GXRvyDcADFq2OeKbhowBzRE+ftAJa96wQdc9718EAU9zo3u7ZGgTrDUMyU1OGYXlXJBM61himtf2Vfjb6FWga3JVvqMpkbWCNOmCRdV8N0kVNV0xFAza/JSZtQLJAbXu8=
  on:
    tags: true
    repo: YoloDev/babel-dts-generator
    node: node
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/290cd344fb3b86aa63cf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
